[package]
name = "perg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perg = { path = "../core", package = "perg-core" }

clap =  { version = "4.5.16", features = ["derive"] }
